# Production Configuration for Challenge Deployment
[server]
host = "0.0.0.0"
port = 8000
workers = 8

[database]
host = "aws-0-ap-southeast-1.pooler.supabase.com"
port = 5432
database = "postgres" 
username = "team9dbuser.jdcgkhwtrsdhyysagkwb"
password = "e5ci7swfjroiqs4f"
max_connections = 50
connect_timeout = 30
idle_timeout = 600
max_lifetime = 1800
ssl_mode = "require"

[performance]
enable_caching = true
cache_size_mb = 512
worker_threads = 8
max_blocking_threads = 16

[monitoring]
enable_metrics = true
log_level = "info"
response_time_buckets = [1.0, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0, 1000.0]

[cache]
price_cache_ttl_seconds = 300      # 5 minutes
calculation_cache_ttl_seconds = 600 # 10 minutes  
correlation_cache_ttl_seconds = 1800 # 30 minutes
max_l1_entries = 100000
max_l2_entries = 50000